export const SeederConfig = {
    ADMINS: 1,
    CLIENTS: 27,
    ARTISTS: 4, 
    APPOINTMENTS: 20,
    SURF_BEGGINER: 1,
    SURF_ADVANCE: 1,
    SKATE_BEGGINER: 1,
    SKATE_ADVANCE: 1,
    SURFSKATE_BEGGINER: 1,
    SURFSKATE_ADVANCE: 1,

  };
